name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    #- name: Build the Docker image
    #  run: docker build . --file ansible2go/Dockerfile --tag devopsteamsdb/devopsteamsdb:ansible2go_$(date +%s)
    
    - name: Login to dockerhub
      uses: docker/login-action@v1
      with:
        #registry: ghcr.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      
